# Importação opcional de configurações locais (não commitadas no Git)
spring.config.import=optional:classpath:application-local.properties

spring.application.name=gameplannerserver
server.port=8080

# ==========================================
# CONFIGURAÇÃO DO POSTGRESQL (Padrão/Produção)
# ==========================================
# Essas configurações serão sobrescritas pelas definidas no 'application-local.properties' localmente.
spring.datasource.url=jdbc:postgresql://localhost:5432/nome_do_banco
spring.datasource.username=usuario
spring.datasource.password=senha
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Flyway (Caso vá usar migrations)
spring.flyway.baseline-on-migrate=true
